### PR TITLE
Modified files with correct import statement to get examply.py to work

### PR DESCRIPTION
**Pull request by gurnaib-brar**
Hi Sergio,

First time I am doing this, not sure if this is correct what I have done, but I needed to do this to get the example.py file to work.

Modified various files with correct import statements to get examply.py to work.

### CODE REVIEW

**Comment by daxm** [comment]
You don't need this if you set your Source Root to be zscaler_api_talker subdir.  This is the more correct way to do it since once the subdir is pushed to pypi it is not longer a "subdir".

Are you using PyCharm?

**Comment by sergitopereira** [comment]
Keep in mind
Most customers install the zscaler-api-talker pip package and do not use pycharm. We need to address this

**Comment by daxm** [comment]
example.py isn’t inthe pypi package.  Thus the user is pulling from github.It is far better to grasp the Universe as it really is than to persist in delusion, however satisfying and reassuring.  — Carl SaganOn Jul 3, 2023, at 18:46, Sergio Pereira ***@***.***> wrote:﻿
Keep in mind
Most customers install the zscaler-api-talker pip package and do not use pycharm. We need to address this

**Comment by gurnaib-brar** [comment]
Hi Sergio,I am not using pycharm. I am using vscode TeagardenGurnaibSent from my iPhoneOn 4 Jul 2023, at 1:34 am, daxm ***@***.***> wrote:﻿
You don't need this if you set your Source Root to be zscaler_api_talker subdir.  This is the more correct way to do it since once the subdir is pushed to pypi it is not longer a "subdir".
Are you using PyCharm?

**Pull request merged**
